### ISSUE TITLE
Shouldn't we use MAMBA?

### ISSUE THREAD

**Issue by ghost** [MR-GREEN1337/Mistral-7b-PyTorch#1]

**Comment by MR-GREEN1337** [comment]
The trend in transformer-based LLMs is shifting towards smaller models with a greater emphasis on the quality of training data. This results in high-performing models with fewer parameters. Additionally, various techniques have been developed to efficiently run these models on CPUs. Moreover, significant investments have been made in developing these types of models. So I wouldn't see them being replaced any time soon.
